In [1]:
import tensorflow as tf
from tensorflow.keras import activations
import numpy as np

# Refer to https://keras.io/api/layers/activations/

In [3]:
x = tf.constant([-10, -5, 0.0, 5, 10], dtype = tf.float32)
x

<tf.Tensor: shape=(5,), dtype=float32, numpy=array([-10.,  -5.,   0.,   5.,  10.], dtype=float32)>

In [4]:
# Relu = max(x, 0)
# resut of the linear op of a layer = [-10.,  -5.,   0.,   5.,  10.]
tf.keras.activations.relu(x)

<tf.Tensor: shape=(5,), dtype=float32, numpy=array([ 0.,  0.,  0.,  5., 10.], dtype=float32)>

In [8]:
# Sigmoid sigmoid(x) = 1 / (1 + exp(-x))
x = tf.constant([-1.5, -1, 0.5, 1, 2], dtype = tf.float32)
np.around(tf.keras.activations.sigmoid(x),4)

array([0.1824, 0.2689, 0.6225, 0.7311, 0.8808], dtype=float32)

In [10]:
# Softmax
x_reshaped = tf.constant([[-1.5, -1, 0.5, 1, 2]], dtype = tf.float32)
print(x_reshaped)
proba = tf.keras.activations.softmax(x_reshaped)
print('proba',np.around(proba,4))
print(tf.reduce_sum(proba) )

tf.Tensor([[-1.5 -1.   0.5  1.   2. ]], shape=(1, 5), dtype=float32)
proba [[0.0181 0.0298 0.1335 0.2202 0.5984]]
tf.Tensor(1.0, shape=(), dtype=float32)
